### ISSUE TITLE
flag.Parse in init() prevents own flags in tests

### ISSUE THREAD

**Issue by breml** [matryer/is#17]
With the commit https://github.com/matryer/is/commit/46663c17c43e9963aa1aae09e7bbdbb35d7b9dda the parsing of the flags has changed to the use of `flag.Parse()`.
Because `flag.Parse()` is called in [`init()`](https://github.com/matryer/is/blob/master/is.go#L78),  it prevents the source package (the one, that uses `github.com/matryer/is`) from defining and using it's own flags, because the calls to e.g. `flag.Bool(...)` will be after the execution of `flag.Parse()` and therefore these flags are not considered and the execution of `go test` fails with `flag provided but not defined: ...`.

This leaves us with two options:

1. Revert the above mentioned commit
2. Under the assumption, that this package is mainly (only) used for testing with `go test`, then it would also be save to remove the call to `flag.Parse()` in `init()`, because `go test` will execute `flag.Parse()`

**Comment by matejb** [comment]
Landed on this problem also so let me give a bit of info after some experimentation.

I like that https://github.com/matryer/is/commit/46663c17c43e9963aa1aae09e7bbdbb35d7b9dda has a proper flag definition, I would move that outside of `init` function and use the flag directly in `New` and `NewRelaxed`. I would delete the `init` function.

Problem with `init` is that flag will not yet be parsed there, that is why https://github.com/matryer/is/commit/46663c17c43e9963aa1aae09e7bbdbb35d7b9dda has a call to `flag.Parse()` in the first place. But once the program is initialized flag `nocolor` will be parsed by `testing` package and because `is` is used only in for testing I think it is ok to rely on this behavior.

Relevant Go spec segment: https://golang.org/ref/spec#Package_initialization

**Comment by matryer** [comment]
Oh wow I didn’t even think of this.

**Comment by breml** [comment]
@matryer how do you like to move forward on this? Do you prefere a PR?

The easiest solution I can think of is to use `flag.BoolVar(&isColorful, ...)` instead of `flag.Bool(...)` and to remove the rest (including the `flag.Parse()`) from `init()`.

**Comment by matryer** [comment]
@breml I'd love a PR on this if you have time?

**Comment by matryer** [comment]
There you go: https://github.com/matryer/is/releases/tag/v1.2.0

**Comment by breml** [comment]
@matryer Thanks again.
