### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by kuchaguangjie** [matryer/is#48]
There are new commits, but no new release or tag for 2 years ...

**Comment by breml** [comment]
@kuchaguangjie Is your question more about if this project is still maintained, or do you just ask for a new tagged release? What is your definition of "alive"?

The pace on this small library is slow, especially because it is considered more or less feature complete, so there is not often the need for a new release.

**Comment by kuchaguangjie** [comment]
If the code is merged, and not released then the code can't be used unless you fork and release yourself.

**Comment by breml** [comment]
This is not quite true, you always have the possibility to use `go get -u github.com/matryer/is@master`, which will add `github.com/matryer/is v1.4.1-0.20220516095740-02e4121244e0` to your go.mod, but I agree, it is better, if there is an official release.

@matryer do you mind to create a new release with the latest state?

**Comment by jeroendee** [comment]
@kuchaguangjie perhaps rename the issue to: "Request for a new official tagged release".

cc @matryer

**Comment by flowchartsman** [comment]
Enjoy! https://github.com/matryer/is/releases/tag/v1.4.1
